// Writes PROFILE.md - the README for the profile repository, generated from data/cv.json so it
// cannot drift from the site. Copy it to github.com/anggiedimasta/anggiedimasta/README.md.
//
//   node make_profile.mjs
//
// It stops at the contact links on purpose. A profile is an introduction, not a documentation
// index: the file table, the test commands and the deploy steps belong in the site repository,
// where someone who has cloned it is actually looking for them. On a profile page they are
// noise. The site repository is anggiedimasta/site.
//
// Why generated rather than hand-written: this is a markdown-only rendering of the same chunks.
// Written by hand it stays right for about a month and then quietly disagrees with the site,
// which is the one failure this project exists to prevent. The answers are identical because
// they are literally the same strings.
//
// No leak check here on purpose: it renders cv.json and nothing else, and test_sec.mjs proves
// cv.json is free of the withheld names. Duplicating that list would be two places to forget.
import { readFileSync, writeFileSync } from "node:fs";

const cv = JSON.parse(readFileSync("data/cv.json", "utf8"));
const byId = new Map(cv.chunks.map((c) => [c.id, c]));
const user = cv.links.github.split("/").pop();

// GitHub's markdown renderer resolves this to a real avatar. It is the one third-party fetch a
// profile README cannot avoid if it shows a face, and GitHub proxies it.
const avatar = `<img src="https://github.com/${user}.png?size=180" width="180" alt="" />`;

const quote = (body) =>
  body.trim().split(/\n{2,}/).map((p) => `> ${p.trim().replace(/\n/g, "\n> ")}`).join("\n>\n");

const featured = cv.featured.map((id) => {
  const c = byId.get(id);
  if (!c) throw new Error(`featured id has no chunk: ${id}`);
  return `### ${c.title}\n\n${quote(c.body)}`;
});

const projects = cv.projects.map((p) => `**${p.name}** — ${p.note}`).join("  \n");

const md = `# ${cv.name}

${avatar}

\`${cv.title}\` · ${cv.location}

${cv.summary}

**Things I have built** — ${projects}

[GitHub](${cv.links.github}) · [LinkedIn](${cv.links.linkedin}) · [${cv.email}](mailto:${cv.email})${cv.phone ? ` · [${cv.phone}](tel:${cv.phone.replace(/[^\d+]/g, "")})` : ""}

---

## Frequently asked

${featured.join("\n\n")}

---

Every answer above is a **verbatim quote** from my CV, not a summary of it. The whole corpus is
[${cv.chunks.length} chunks of JSON](https://github.com/${user}/site/blob/main/data/cv.json), each with the questions it
answers, and a BM25 scorer picks the one that fits — with no language model in the loop, so
nothing here can be invented. It is also the website: it answers questions in the browser with no
server, no API key and no bill.

<sub>Generated by <code>make_profile.mjs</code> from <code>data/cv.json</code> in
<a href="https://github.com/${user}/site">${user}/site</a>. Edit the JSON, not this file.</sub>
`;

writeFileSync("PROFILE.md", md);
console.log(`PROFILE.md  ${md.split("\n").length} lines, ${md.length} chars, ${cv.featured.length} featured, stops at contact`);
